### ISSUE TITLE
No validator here as in Textform field

### ISSUE THREAD

**Issue by imnimeshdev** [deekshithx/animated_hint_textfield#3]
Hi, It's very beautiful. Very Nice. The only problem is there is no validator. How can I set it as mandatory field. Please kindly add validation as in textform field. Loved it.

**Comment by deekshithx** [comment]
Hi @imnimeshdev  Thanks for reporting this issue.
Validator has been added in the new version of [animated_hint_textfield](https://pub.dev/packages/animated_hint_textfield)
Feel free to reopen the issue if problem presists.
